r2/iRob_Interface:
    ros__parameters:
        serial_port:            "/dev/iRob"
        robot_frame_id:         "base_link_r2"
        mouse_odom_frame_id:    "mouse_odom_r2"
        imu_frame_id:           "imu_link_r2"
        mag_sensor_topic:       "imu/mag_r2"
        imu_sensor_topic:       "imu/data_raw_r2"
        mouse_x_constant:       0.03
        mouse_y_constant:       0.03
        gyro_constant:          0.0010642
        mag_constant:           0.08075
        accel_constant:         0.000488
