urg_node:
  ros__parameters:
    serial_port: "/dev/hokuyo_B2100082"
    laser_frame_id: "laser_frame2_r2"
    laser_topic: "/scan_hokuyo2_r2"
    angle_offset: 0.0
    min_angle: -1.570796  # 90 degree
    max_angle: 1.570796   # 90 degree
