urg_node:
  ros__parameters:
    serial_port: "/dev/hokuyo"
    laser_frame_id: "laser_frame_r1"
    laser_topic: "/scan_hokuyo_r1"
    angle_offset: 0.0
    min_angle: -1.448623  # 80 degree
    max_angle: 1.448623   # 80 degree
