urg_node:
  ros__parameters:
    serial_port: "/dev/hokuyo_L2204511"
    laser_frame_id: "laser_frame1_r2"
    laser_topic: "/scan_1"
    angle_offset: 0.0
    min_angle: -1.48353  # -85 degree
    max_angle: 1.48353   # 85 degree
