iRob_controller:
  ros__parameters:
    robot_frame_id: "base_link_r1"
    odom_frame_id: "odom_r1"
    irob_holo_type: 2
    robot_width: 0.215
    robot_length: 0.13
    wheel_radius: 0.05
    gear_ratio: 82.00
    publish_tf: false   # Let the EFK publish transfor instead
