urg_node:
  ros__parameters:
    serial_port: "/dev/hokuyo_L2204511"
    laser_frame_id: "laser_frame1_r1"
    laser_topic: "/scan_1"
    angle_offset: 0.0
    min_angle: -2.356194  # 135 degree
    max_angle: 1.658063   # 95 degree
