urg_node:
  ros__parameters:
    serial_port: "/dev/hokuyo"
    laser_frame_id: "laser_frame_r1"
    laser_topic: "/scan_hokuyo_r1"
    angle_offset: 0.0
    min_angle: -2.356194  # 135 degree
    max_angle: 1.658063   # 95 degree
